version: '3.8'

services:
  nginx:
    image: nginx:latest
    ports:
      - "80:80"

  app:
    build: 
      dockerfile: ./php/Dockerfile

  memcached:
    image: memcached:latest
    ports:
      - "11211:11211"
